### ISSUE TITLE
cmake-config patch

### ISSUE THREAD

**Issue by looooo** [coin3d/superglu#10]
To build superglue as a conda-package I had to make the following modification. Not sure if this should be applied:

```
-set_and_check(@PROJECT_NAME@_LIBRARY_DIRS "@PACKAGE_CMAKE_INSTALL_LIBDIR@")
+set_and_check(@PROJECT_NAME@_LIBRARY_DIRS "@CMAKE_INSTALL_LIBDIR@")
```

https://github.com/coin3d/superglu/blob/master/superglu-config.cmake.in#L46

**Comment by VolkerEnderlein** [comment]
Thanks for the provided patch. I checked the cause for the missing variable and added the missing line to the CMakeLists.txt with commit d26d84cb50e9c19b8d24acfee9399958876ad537
